### ISSUE TITLE
Investigate replacing OneSignal for FirebaseMessaging

### ISSUE THREAD

**Issue by lifenautjoe** [OkunaOrg/okuna-app#423]
OneSignal for Flutter has been unreliable in the past with outdated docs and outdated APIs plus it's currently broken for 2 months https://github.com/OneSignal/OneSignal-Flutter-SDK/issues/127 and impeding any release.

OneSignal uses Firebase behind the scenes anyway. Investigate effort needed to change provider.

**Comment by lifenautjoe** [comment]
Managed to fix one signal issue by modifying the package...

**Comment by adambeck7** [comment]
@lifenautjoe what exactly did you do to solve the issue? I'm having the same error on React Native .61.1.

**Comment by lifenautjoe** [comment]
Hi @adambeck7 .

* I updated the plugin classpath as seen here https://github.com/OkunaOrg/okuna-app/blob/develop/android/app/build.gradle#L9
* Changed the the bottom dependencies section from compile to implementation as seen here https://github.com/OkunaOrg/okuna-app/blob/develop/android/app/build.gradle#L106
* Forked the OneSignal plugin and changed the compile to implementation as seen here https://github.com/OkunaOrg/OneSignal-Flutter-SDK/commit/58fccdcc0e872a10c6313e22e1f885f58f793bd4

Also to note, we're using gradle-5.4.1. We had to update to make our project work on `flutter channel master`. The last compile to implementation step might be related only to this and not to one signal itself.

We changed this on the `gradle-wrapper.properties`
```
distributionUrl=https\://services.gradle.org/distributions/gradle-5.4.1-all.zip
```

Let me know if this helps.

**Comment by adambeck7** [comment]
Thanks for the reply. I had updated the plugin and moved the implementation to the end of the file and unfortunately (for me) the RN SDK doesn't have the same compile/implementation issue and I'm still getting the same error. Thanks for getting back to me though.
